// Comprehensive list of countries and nationalities
export interface Country {
  code: string;
  name: string;
  dialCode: string;
  nationality: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", dialCode: "+93", nationality: "Afghan" },
  { code: "AL", name: "Albania", dialCode: "+355", nationality: "Albanian" },
  { code: "DZ", name: "Algeria", dialCode: "+213", nationality: "Algerian" },
  { code: "AS", name: "American Samoa", dialCode: "+1", nationality: "American Samoan" },
  { code: "AD", name: "Andorra", dialCode: "+376", nationality: "Andorran" },
  { code: "AO", name: "Angola", dialCode: "+244", nationality: "Angolan" },
  { code: "AI", name: "Anguilla", dialCode: "+1", nationality: "Anguillan" },
  { code: "AG", name: "Antigua and Barbuda", dialCode: "+1", nationality: "Antiguan/Barbudan" },
  { code: "AR", name: "Argentina", dialCode: "+54", nationality: "Argentinian" },
  { code: "AM", name: "Armenia", dialCode: "+374", nationality: "Armenian" },
  { code: "AW", name: "Aruba", dialCode: "+297", nationality: "Aruban" },
  { code: "AU", name: "Australia", dialCode: "+61", nationality: "Australian" },
  { code: "AT", name: "Austria", dialCode: "+43", nationality: "Austrian" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994", nationality: "Azerbaijani" },
  { code: "BS", name: "Bahamas", dialCode: "+1", nationality: "Bahamian" },
  { code: "BH", name: "Bahrain", dialCode: "+973", nationality: "Bahraini" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", nationality: "Bangladeshi" },
  { code: "BB", name: "Barbados", dialCode: "+1", nationality: "Barbadian" },
  { code: "BY", name: "Belarus", dialCode: "+375", nationality: "Belarusian" },
  { code: "BE", name: "Belgium", dialCode: "+32", nationality: "Belgian" },
  { code: "BZ", name: "Belize", dialCode: "+501", nationality: "Belizean" },
  { code: "BJ", name: "Benin", dialCode: "+229", nationality: "Beninese" },
  { code: "BM", name: "Bermuda", dialCode: "+1", nationality: "Bermudian" },
  { code: "BT", name: "Bhutan", dialCode: "+975", nationality: "Bhutanese" },
  { code: "BO", name: "Bolivia", dialCode: "+591", nationality: "Bolivian" },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", nationality: "Bosnian/Herzegovinian" },
  { code: "BW", name: "Botswana", dialCode: "+267", nationality: "Botswanan" },
  { code: "BR", name: "Brazil", dialCode: "+55", nationality: "Brazilian" },
  { code: "BN", name: "Brunei", dialCode: "+673", nationality: "Bruneian" },
  { code: "BG", name: "Bulgaria", dialCode: "+359", nationality: "Bulgarian" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", nationality: "Burkinabé" },
  { code: "BI", name: "Burundi", dialCode: "+257", nationality: "Burundian" },
  { code: "CV", name: "Cabo Verde", dialCode: "+238", nationality: "Cape Verdean" },
  { code: "KH", name: "Cambodia", dialCode: "+855", nationality: "Cambodian" },
  { code: "CM", name: "Cameroon", dialCode: "+237", nationality: "Cameroonian" },
  { code: "CA", name: "Canada", dialCode: "+1", nationality: "Canadian" },
  { code: "KY", name: "Cayman Islands", dialCode: "+1", nationality: "Caymanian" },
  { code: "CF", name: "Central African Republic", dialCode: "+236", nationality: "Central African" },
  { code: "TD", name: "Chad", dialCode: "+235", nationality: "Chadian" },
  { code: "CL", name: "Chile", dialCode: "+56", nationality: "Chilean" },
  { code: "CN", name: "China", dialCode: "+86", nationality: "Chinese" },
  { code: "CO", name: "Colombia", dialCode: "+57", nationality: "Colombian" },
  { code: "KM", name: "Comoros", dialCode: "+269", nationality: "Comoran" },
  { code: "CG", name: "Congo", dialCode: "+242", nationality: "Congolese (Republic)" },
  { code: "CD", name: "Congo (DRC)", dialCode: "+243", nationality: "Congolese (DRC)" },
  { code: "CR", name: "Costa Rica", dialCode: "+506", nationality: "Costa Rican" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225", nationality: "Ivorian" },
  { code: "HR", name: "Croatia", dialCode: "+385", nationality: "Croatian" },
  { code: "CU", name: "Cuba", dialCode: "+53", nationality: "Cuban" },
  { code: "CW", name: "Curaçao", dialCode: "+599", nationality: "Curaçaoan" },
  { code: "CY", name: "Cyprus", dialCode: "+357", nationality: "Cypriot" },
  { code: "CZ", name: "Czech Republic", dialCode: "+420", nationality: "Czech" },
  { code: "DK", name: "Denmark", dialCode: "+45", nationality: "Danish" },
  { code: "DJ", name: "Djibouti", dialCode: "+253", nationality: "Djiboutian" },
  { code: "DM", name: "Dominica", dialCode: "+1", nationality: "Dominican (Dominica)" },
  { code: "DO", name: "Dominican Republic", dialCode: "+1", nationality: "Dominican" },
  { code: "EC", name: "Ecuador", dialCode: "+593", nationality: "Ecuadorian" },
  { code: "EG", name: "Egypt", dialCode: "+20", nationality: "Egyptian" },
  { code: "SV", name: "El Salvador", dialCode: "+503", nationality: "Salvadoran" },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", nationality: "Equatoguinean" },
  { code: "ER", name: "Eritrea", dialCode: "+291", nationality: "Eritrean" },
  { code: "EE", name: "Estonia", dialCode: "+372", nationality: "Estonian" },
  { code: "SZ", name: "Eswatini", dialCode: "+268", nationality: "Swazi" },
  { code: "ET", name: "Ethiopia", dialCode: "+251", nationality: "Ethiopian" },
  { code: "FJ", name: "Fiji", dialCode: "+679", nationality: "Fijian" },
  { code: "FI", name: "Finland", dialCode: "+358", nationality: "Finnish" },
  { code: "FR", name: "France", dialCode: "+33", nationality: "French" },
  { code: "GA", name: "Gabon", dialCode: "+241", nationality: "Gabonese" },
  { code: "GM", name: "Gambia", dialCode: "+220", nationality: "Gambian" },
  { code: "GE", name: "Georgia", dialCode: "+995", nationality: "Georgian" },
  { code: "DE", name: "Germany", dialCode: "+49", nationality: "German" },
  { code: "GH", name: "Ghana", dialCode: "+233", nationality: "Ghanaian" },
  { code: "GR", name: "Greece", dialCode: "+30", nationality: "Greek" },
  { code: "GD", name: "Grenada", dialCode: "+1", nationality: "Grenadian" },
  { code: "GT", name: "Guatemala", dialCode: "+502", nationality: "Guatemalan" },
  { code: "GN", name: "Guinea", dialCode: "+224", nationality: "Guinean" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245", nationality: "Guinea-Bissauan" },
  { code: "GY", name: "Guyana", dialCode: "+592", nationality: "Guyanese" },
  { code: "HT", name: "Haiti", dialCode: "+509", nationality: "Haitian" },
  { code: "HN", name: "Honduras", dialCode: "+504", nationality: "Honduran" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", nationality: "Hong Kongese" },
  { code: "HU", name: "Hungary", dialCode: "+36", nationality: "Hungarian" },
  { code: "IS", name: "Iceland", dialCode: "+354", nationality: "Icelandic" },
  { code: "IN", name: "India", dialCode: "+91", nationality: "Indian" },
  { code: "ID", name: "Indonesia", dialCode: "+62", nationality: "Indonesian" },
  { code: "IR", name: "Iran", dialCode: "+98", nationality: "Iranian" },
  { code: "IQ", name: "Iraq", dialCode: "+964", nationality: "Iraqi" },
  { code: "IE", name: "Ireland", dialCode: "+353", nationality: "Irish" },
  { code: "IL", name: "Israel", dialCode: "+972", nationality: "Israeli" },
  { code: "IT", name: "Italy", dialCode: "+39", nationality: "Italian" },
  { code: "JM", name: "Jamaica", dialCode: "+1", nationality: "Jamaican" },
  { code: "JP", name: "Japan", dialCode: "+81", nationality: "Japanese" },
  { code: "JO", name: "Jordan", dialCode: "+962", nationality: "Jordanian" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7", nationality: "Kazakhstani" },
  { code: "KE", name: "Kenya", dialCode: "+254", nationality: "Kenyan" },
  { code: "KI", name: "Kiribati", dialCode: "+686", nationality: "I-Kiribati" },
  { code: "KP", name: "North Korea", dialCode: "+850", nationality: "North Korean" },
  { code: "KR", name: "South Korea", dialCode: "+82", nationality: "South Korean" },
  { code: "KW", name: "Kuwait", dialCode: "+965", nationality: "Kuwaiti" },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996", nationality: "Kyrgyzstani" },
  { code: "LA", name: "Laos", dialCode: "+856", nationality: "Laotian" },
  { code: "LV", name: "Latvia", dialCode: "+371", nationality: "Latvian" },
  { code: "LB", name: "Lebanon", dialCode: "+961", nationality: "Lebanese" },
  { code: "LS", name: "Lesotho", dialCode: "+266", nationality: "Basotho" },
  { code: "LR", name: "Liberia", dialCode: "+231", nationality: "Liberian" },
  { code: "LY", name: "Libya", dialCode: "+218", nationality: "Libyan" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423", nationality: "Liechtensteiner" },
  { code: "LT", name: "Lithuania", dialCode: "+370", nationality: "Lithuanian" },
  { code: "LU", name: "Luxembourg", dialCode: "+352", nationality: "Luxembourgish" },
  { code: "MO", name: "Macao", dialCode: "+853", nationality: "Macanese" },
  { code: "MG", name: "Madagascar", dialCode: "+261", nationality: "Malagasy" },
  { code: "MW", name: "Malawi", dialCode: "+265", nationality: "Malawian" },
  { code: "MY", name: "Malaysia", dialCode: "+60", nationality: "Malaysian" },
  { code: "MV", name: "Maldives", dialCode: "+960", nationality: "Maldivian" },
  { code: "ML", name: "Mali", dialCode: "+223", nationality: "Malian" },
  { code: "MT", name: "Malta", dialCode: "+356", nationality: "Maltese" },
  { code: "MH", name: "Marshall Islands", dialCode: "+692", nationality: "Marshallese" },
  { code: "MR", name: "Mauritania", dialCode: "+222", nationality: "Mauritanian" },
  { code: "MU", name: "Mauritius", dialCode: "+230", nationality: "Mauritian" },
  { code: "MX", name: "Mexico", dialCode: "+52", nationality: "Mexican" },
  { code: "FM", name: "Micronesia", dialCode: "+691", nationality: "Micronesian" },
  { code: "MD", name: "Moldova", dialCode: "+373", nationality: "Moldovan" },
  { code: "MC", name: "Monaco", dialCode: "+377", nationality: "Monégasque" },
  { code: "MN", name: "Mongolia", dialCode: "+976", nationality: "Mongolian" },
  { code: "ME", name: "Montenegro", dialCode: "+382", nationality: "Montenegrin" },
  { code: "MA", name: "Morocco", dialCode: "+212", nationality: "Moroccan" },
  { code: "MZ", name: "Mozambique", dialCode: "+258", nationality: "Mozambican" },
  { code: "MM", name: "Myanmar", dialCode: "+95", nationality: "Myanmar" },
  { code: "NA", name: "Namibia", dialCode: "+264", nationality: "Namibian" },
  { code: "NR", name: "Nauru", dialCode: "+674", nationality: "Nauruan" },
  { code: "NP", name: "Nepal", dialCode: "+977", nationality: "Nepalese" },
  { code: "NL", name: "Netherlands", dialCode: "+31", nationality: "Dutch" },
  { code: "NZ", name: "New Zealand", dialCode: "+64", nationality: "New Zealander" },
  { code: "NI", name: "Nicaragua", dialCode: "+505", nationality: "Nicaraguan" },
  { code: "NE", name: "Niger", dialCode: "+227", nationality: "Nigerien" },
  { code: "NG", name: "Nigeria", dialCode: "+234", nationality: "Nigerian" },
  { code: "MK", name: "North Macedonia", dialCode: "+389", nationality: "Macedonian" },
  { code: "NO", name: "Norway", dialCode: "+47", nationality: "Norwegian" },
  { code: "OM", name: "Oman", dialCode: "+968", nationality: "Omani" },
  { code: "PK", name: "Pakistan", dialCode: "+92", nationality: "Pakistani" },
  { code: "PW", name: "Palau", dialCode: "+680", nationality: "Palauan" },
  { code: "PS", name: "Palestine", dialCode: "+970", nationality: "Palestinian" },
  { code: "PA", name: "Panama", dialCode: "+507", nationality: "Panamanian" },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675", nationality: "Papua New Guinean" },
  { code: "PY", name: "Paraguay", dialCode: "+595", nationality: "Paraguayan" },
  { code: "PE", name: "Peru", dialCode: "+51", nationality: "Peruvian" },
  { code: "PH", name: "Philippines", dialCode: "+63", nationality: "Filipino" },
  { code: "PL", name: "Poland", dialCode: "+48", nationality: "Polish" },
  { code: "PT", name: "Portugal", dialCode: "+351", nationality: "Portuguese" },
  { code: "QA", name: "Qatar", dialCode: "+974", nationality: "Qatari" },
  { code: "RO", name: "Romania", dialCode: "+40", nationality: "Romanian" },
  { code: "RU", name: "Russia", dialCode: "+7", nationality: "Russian" },
  { code: "RW", name: "Rwanda", dialCode: "+250", nationality: "Rwandan" },
  { code: "KN", name: "Saint Kitts and Nevis", dialCode: "+1", nationality: "Kittitian/Nevisian" },
  { code: "LC", name: "Saint Lucia", dialCode: "+1", nationality: "Saint Lucian" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1", nationality: "Saint Vincentian" },
  { code: "WS", name: "Samoa", dialCode: "+685", nationality: "Samoan" },
  { code: "SM", name: "San Marino", dialCode: "+378", nationality: "Sammarinese" },
  { code: "ST", name: "São Tomé and Príncipe", dialCode: "+239", nationality: "Santomean" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", nationality: "Saudi Arabian" },
  { code: "SN", name: "Senegal", dialCode: "+221", nationality: "Senegalese" },
  { code: "RS", name: "Serbia", dialCode: "+381", nationality: "Serbian" },
  { code: "SC", name: "Seychelles", dialCode: "+248", nationality: "Seychellois" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", nationality: "Sierra Leonean" },
  { code: "SG", name: "Singapore", dialCode: "+65", nationality: "Singaporean" },
  { code: "SK", name: "Slovakia", dialCode: "+421", nationality: "Slovak" },
  { code: "SI", name: "Slovenia", dialCode: "+386", nationality: "Slovenian" },
  { code: "SB", name: "Solomon Islands", dialCode: "+677", nationality: "Solomon Islander" },
  { code: "SO", name: "Somalia", dialCode: "+252", nationality: "Somali" },
  { code: "ZA", name: "South Africa", dialCode: "+27", nationality: "South African" },
  { code: "SS", name: "South Sudan", dialCode: "+211", nationality: "South Sudanese" },
  { code: "ES", name: "Spain", dialCode: "+34", nationality: "Spanish" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", nationality: "Sri Lankan" },
  { code: "SD", name: "Sudan", dialCode: "+249", nationality: "Sudanese" },
  { code: "SR", name: "Suriname", dialCode: "+597", nationality: "Surinamese" },
  { code: "SE", name: "Sweden", dialCode: "+46", nationality: "Swedish" },
  { code: "CH", name: "Switzerland", dialCode: "+41", nationality: "Swiss" },
  { code: "SY", name: "Syria", dialCode: "+963", nationality: "Syrian" },
  { code: "TW", name: "Taiwan", dialCode: "+886", nationality: "Taiwanese" },
  { code: "TJ", name: "Tajikistan", dialCode: "+992", nationality: "Tajikistani" },
  { code: "TZ", name: "Tanzania", dialCode: "+255", nationality: "Tanzanian" },
  { code: "TH", name: "Thailand", dialCode: "+66", nationality: "Thai" },
  { code: "TL", name: "Timor-Leste", dialCode: "+670", nationality: "Timorese" },
  { code: "TG", name: "Togo", dialCode: "+228", nationality: "Togolese" },
  { code: "TO", name: "Tonga", dialCode: "+676", nationality: "Tongan" },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "+1", nationality: "Trinidadian/Tobagonian" },
  { code: "TN", name: "Tunisia", dialCode: "+216", nationality: "Tunisian" },
  { code: "TR", name: "Turkey", dialCode: "+90", nationality: "Turkish" },
  { code: "TM", name: "Turkmenistan", dialCode: "+993", nationality: "Turkmen" },
  { code: "TV", name: "Tuvalu", dialCode: "+688", nationality: "Tuvaluan" },
  { code: "UG", name: "Uganda", dialCode: "+256", nationality: "Ugandan" },
  { code: "UA", name: "Ukraine", dialCode: "+380", nationality: "Ukrainian" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971", nationality: "Emirati" },
  { code: "GB", name: "United Kingdom", dialCode: "+44", nationality: "British" },
  { code: "US", name: "United States", dialCode: "+1", nationality: "American" },
  { code: "UY", name: "Uruguay", dialCode: "+598", nationality: "Uruguayan" },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998", nationality: "Uzbekistani" },
  { code: "VU", name: "Vanuatu", dialCode: "+678", nationality: "Ni-Vanuatu" },
  { code: "VA", name: "Vatican City", dialCode: "+39", nationality: "Vatican" },
  { code: "VE", name: "Venezuela", dialCode: "+58", nationality: "Venezuelan" },
  { code: "VN", name: "Vietnam", dialCode: "+84", nationality: "Vietnamese" },
  { code: "YE", name: "Yemen", dialCode: "+967", nationality: "Yemeni" },
  { code: "ZM", name: "Zambia", dialCode: "+260", nationality: "Zambian" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", nationality: "Zimbabwean" }
];

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(country => country.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return COUNTRIES.find(country => country.name.toLowerCase() === name.toLowerCase());
};

export const getNationalityByCountry = (countryName: string): string => {
  const country = getCountryByName(countryName);
  return country?.nationality || '';
};

export const getAllCountryNames = (): string[] => {
  return COUNTRIES.map(country => country.name).sort();
};

export const getAllNationalities = (): string[] => {
  return COUNTRIES.map(country => country.nationality).sort();
};

export const searchCountries = (query: string): Country[] => {
  const lowerQuery = query.toLowerCase();
  return COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.nationality.toLowerCase().includes(lowerQuery)
  );
};